workspace(name = "wtf_agent_extension")

#load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Proxy SDK. 2022-03-15, as in envoy v1.23.1
#PROXY_WASM_CPP_SDK_SHA = "e30535b7c0cd3126e6401bc3769063a74bbb37be"

#PROXY_WASM_CPP_SDK_SHA256 = "94e474ebea782225821224734ed5992fa749301e12e06b6520b8b4d4e1c05ffc"

#http_archive(
#    name = "proxy_wasm_cpp_sdk",
#    sha256 = PROXY_WASM_CPP_SDK_SHA256,
#    strip_prefix = "proxy-wasm-cpp-sdk-" + PROXY_WASM_CPP_SDK_SHA,
#    url = "https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/archive/" + PROXY_WASM_CPP_SDK_SHA + ".tar.gz",
#)

#load("@proxy_wasm_cpp_sdk//bazel/dep:deps.bzl", "wasm_dependencies")

#wasm_dependencies()

#load("@proxy_wasm_cpp_sdk//bazel/dep:deps_extra.bzl", "wasm_dependencies_extra")

#wasm_dependencies_extra()
